
package com.unionpay.sms.utils;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMSMessageServiceService", targetNamespace = "http://www.primeton.com/SMSMessageServiceService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSMessageServiceService {


    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns com.unionpay.portal.meets.smsMessageService.WMResult
     */
    @WebMethod
    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/SMSMessageServiceService")
    @RequestWrapper(localName = "send", targetNamespace = "http://www.primeton.com/SMSMessageServiceService", className = "com.unionpay.portal.meets.smsMessageService.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://www.primeton.com/SMSMessageServiceService", className = "com.unionpay.portal.meets.smsMessageService.SendResponse")
    public WMResult send(
            @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/SMSMessageServiceService")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "http://www.primeton.com/SMSMessageServiceService")
                    ArrayOfString in1);

}
